### ISSUE TITLE
scamp crashes during import

### ISSUE THREAD

**Issue by shimpe** [MarcTheSpark/scamp#3]
I seem to hit a problem where during import scamp tries to create settings files (json format) in the package folder. Since that is typically not writable on linux systems, it crashes during import. 

I think settings files by default should be read/created in the user's home folder (a subfolder of the home folder) instead.

**Comment by MarcTheSpark** [comment]
Hmm... was this with the 0.8.7 release on pip? I changed something about how the settings work, but I imagine this would have been a problem with earlier versions too.

Also, did you you use `pip3 install` or `pip3 install --user`?

At any rate, I suspect that you may be right about where the files are stored... The question is what the best cross-platform way to find the correct location is.

**Comment by MarcTheSpark** [comment]
Update: I think I've found a good cross-platform way to do this, based on: https://github.com/SwagLyrics/SwagLyrics-For-Spotify/blob/master/swaglyrics/__init__.py#L8-L32

I'll change it in the next release. Thanks for the suggestion!

**Comment by shimpe** [comment]
Hi Marc,

An "official" cross-platform way to find the user's home folder would be to:

from os.path import expanduser
home = expanduser("~")

If you're on *Python 3.5+* you can use pathlib.Path.home()
<https://docs.python.org/3/library/pathlib.html#pathlib.Path.home>
